# -*- coding: utf-8 -*-
"""Tutorial7_Task3and4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12KEg7DgEhJTKWxxaFhhq4c9ysSl7hK_i

# Task 3
Execute the following code, then add additional words to see where they get placed in the Word Embeddings Cloud.
"""

!pip install sentence_transformers

import numpy as np
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA

model = SentenceTransformer(
    "sentence-transformers/all-MiniLM-L6-v2",
    token=False
)

words = [
    "dog", "cat", "horse", "mouse",
    "apple", "banana", "orange", "cake",
    "university", "lecture", "exam", "student",
    "transformer", "attention", "embedding", "retrieval",
    "database", "document", "question", "answer"
]

embeddings = model.encode(words)

pca = PCA(n_components=2)
embeddings_2d = pca.fit_transform(embeddings)

plt.figure(figsize=(10, 7))
plt.scatter(embeddings_2d[:, 0], embeddings_2d[:, 1])

for i, word in enumerate(words):
    plt.annotate(word, (embeddings_2d[i, 0], embeddings_2d[i, 1]))

plt.title("Word Embeddings projected to 2D using PCA")
plt.xlabel("PCA dimension 1")
plt.ylabel("PCA dimension 2")
plt.grid(True)
plt.show()

from IPython.display import clear_output

cloud_words = []
cloud_embeddings = []

# Use a fixed PCA basis from the larger vocabulary above
pca_fixed = PCA(n_components=2)
pca_fixed.fit(embeddings)

def add_word(word):
    word = word.strip()

    if not word:
        print("Please enter a word.")
        return

    if word in cloud_words:
        print(f"'{word}' is already in the cloud.")
        return

    emb = model.encode([word])[0]

    cloud_words.append(word)
    cloud_embeddings.append(emb)

    clear_output(wait=True)

    X = np.array(cloud_embeddings)
    X_2d = pca_fixed.transform(X)

    plt.figure(figsize=(10, 7))
    plt.scatter(X_2d[:, 0], X_2d[:, 1])

    for i, w in enumerate(cloud_words):
        plt.annotate(w, (X_2d[i, 0], X_2d[i, 1]))

    plt.title("Growing Embedding Cloud")
    plt.xlabel("PCA dimension 1")
    plt.ylabel("PCA dimension 2")
    plt.grid(True)
    plt.show()

    print("Words in cloud:", cloud_words)

add_word("dog")

add_word("apple")

add_word("cat")

add_word("banana")

add_word("transformer")

add_word("attention")

add_word("retrieval")

add_word("database")
add_word("university")
add_word("exam")

"""a) Find at least one word that can have two different meanings and thus might get placed in a weird position."""

# Add a word below
add_word("")

"""b) Find two words that are different but can have similar contexts so that they might get placed closely together."""

# Add more words below
add_word("")
add_word("")

"""c) Add additional words that you want to integrate into the word cloud."""

# Add a word below
add_word("")

"""# Task 4
In this task, you will experiment with RAG.
"""

import logging
import numpy as np
import matplotlib.pyplot as plt

from transformers.utils import logging as hf_logging
from sentence_transformers import SentenceTransformer
from sklearn.decomposition import PCA
from sklearn.metrics.pairwise import cosine_similarity

logging.getLogger("sentence_transformers").setLevel(logging.ERROR)
hf_logging.set_verbosity_error()

model = SentenceTransformer("sentence-transformers/all-MiniLM-L6-v2")

test = model.encode(["dog", "cat", "transformer"])
print("Model loaded successfully.")
print("Test embedding shape:", test.shape)

chunks = [
    "The lecture introduces transformers and attention mechanisms.",
    "Retrieval augmented generation uses external documents as context.",
    "The exam contains conceptual questions and small calculations.",
    "Neural networks are trained using gradient descent.",
    "Recurrent neural networks process sequential data.",
    "Embeddings represent words or texts as high-dimensional vectors.",
]

chunk_embeddings = model.encode(chunks)

print("Chunk embeddings shape:", chunk_embeddings.shape)

def retrieve_and_plot(query, top_k=3):
    query_embedding = model.encode([query])

    similarities = cosine_similarity(query_embedding, chunk_embeddings)[0]

    top_indices = np.argsort(similarities)[::-1][:top_k]

    print("Query:")
    print(query)
    print("\nTop retrieved chunks:")

    for rank, idx in enumerate(top_indices, start=1):
        print(f"{rank}. Score: {similarities[idx]:.3f}")
        print(chunks[idx])
        print()

    all_embeddings = np.vstack([chunk_embeddings, query_embedding])

    pca = PCA(n_components=2)
    all_2d = pca.fit_transform(all_embeddings)

    chunk_2d = all_2d[:-1]
    query_2d = all_2d[-1]

    plt.figure(figsize=(9, 6))

    plt.scatter(chunk_2d[:, 0], chunk_2d[:, 1], label="Document chunks")
    plt.scatter(query_2d[0], query_2d[1], marker="x", s=120, label="Query")

    for i, chunk in enumerate(chunks):
        plt.annotate(f"Chunk {i+1}", (chunk_2d[i, 0], chunk_2d[i, 1]))

    plt.annotate("Query", (query_2d[0], query_2d[1]))

    for idx in top_indices:
        plt.plot(
            [query_2d[0], chunk_2d[idx, 0]],
            [query_2d[1], chunk_2d[idx, 1]],
            linestyle="--"
        )

    plt.title("Query and Retrieved Chunks in Embedding Space")
    plt.xlabel("PCA Dimension 1")
    plt.ylabel("PCA Dimension 2")
    plt.legend()
    plt.grid(True)
    plt.show()

"""a) Enter three different queries that can be answered with the help of the RAG system."""

# for example:
retrieve_and_plot("How does RAG use external documents?")
# Add more...

"""b) Add additional information about a topic of your choice to the RAG system that the system can use to answer queries."""

chunks = [
    "The lecture introduces transformers and attention mechanisms.",
    "Retrieval augmented generation uses external documents as context.",
    "The exam contains conceptual questions and small calculations.",
    "Neural networks are trained using gradient descent.",
    "Recurrent neural networks process sequential data.",
    "Embeddings represent words or texts as high-dimensional vectors.",
]

chunk_embeddings = model.encode(chunks)

print("Chunk embeddings shape:", chunk_embeddings.shape)

"""c) Create three queries that can be answered with the help of your adapted RAG system."""

retrieve_and_plot("")
# Add more...